# Generated by Django 5.0.6 on 2024-07-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHernan', '0002_socio_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
